### ISSUE TITLE
This looks really complicated.

### ISSUE THREAD

**Issue by Chris1221** [MartinLunn/COMP2401#1]
That's all.

**Comment by MartinLunn** [comment]
Thank you for your bug report, unfortunately, we won't be supporting a simpler view in the foreseeable future. If you think this looks complicated, please gitgud, and try again. ;)

Thank you for your time.

**Comment by Chris1221** [comment]
Dear maintainer:

I have attempted your proposed solution, though when I attempt to run

```
git --gud
```

the command fails citing an unhandled exception. It tells me that it cannot resolve `gud` and suggests that the resource is either corrupt or does not exist. Could you propose an addendum?
